from .plan_node import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .reference_router import (
    NODE_CLASS_MAPPINGS as REFERENCE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as REFERENCE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .h3_aux_device import (
    NODE_CLASS_MAPPINGS as AUX_DEVICE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as AUX_DEVICE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .normalized_save import (
    NODE_CLASS_MAPPINGS as NORMALIZED_SAVE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as NORMALIZED_SAVE_NODE_DISPLAY_NAME_MAPPINGS,
)
from . import routes as _routes  # noqa: F401 - registers HTTP assembly routes

WEB_DIRECTORY = "./web_v90"

NODE_CLASS_MAPPINGS.update(REFERENCE_NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(REFERENCE_NODE_DISPLAY_NAME_MAPPINGS)
NODE_CLASS_MAPPINGS.update(AUX_DEVICE_NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(AUX_DEVICE_NODE_DISPLAY_NAME_MAPPINGS)
NODE_CLASS_MAPPINGS.update(NORMALIZED_SAVE_NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(NORMALIZED_SAVE_NODE_DISPLAY_NAME_MAPPINGS)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
