from .plan_node import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .reference_router import (
    NODE_CLASS_MAPPINGS as REFERENCE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as REFERENCE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .h3_aux_device import (
    NODE_CLASS_MAPPINGS as AUX_DEVICE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as AUX_DEVICE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .normalized_save import (
    NODE_CLASS_MAPPINGS as NORMALIZED_SAVE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as NORMALIZED_SAVE_NODE_DISPLAY_NAME_MAPPINGS,
)
from . import routes as _routes  # noqa: F401 - registers HTTP assembly routes
from .postprocess_nodes import (
    NODE_CLASS_MAPPINGS as POSTPROCESS_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as POSTPROCESS_NODE_DISPLAY_NAME_MAPPINGS,
)
from .keyframe_node import (
    NODE_CLASS_MAPPINGS as KEYFRAME_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as KEYFRAME_NODE_DISPLAY_NAME_MAPPINGS,
)

WEB_DIRECTORY = "./web_v90"
from .import_cache import NODE_CLASS_MAPPINGS as IMPORT_CACHE_NODES, NODE_DISPLAY_NAME_MAPPINGS as IMPORT_CACHE_NAMES
NODE_CLASS_MAPPINGS.update(IMPORT_CACHE_NODES)
NODE_DISPLAY_NAME_MAPPINGS.update(IMPORT_CACHE_NAMES)

from .h3_turbo_loader import NODE_CLASS_MAPPINGS as TURBO_NODES, NODE_DISPLAY_NAME_MAPPINGS as TURBO_NAMES
NODE_CLASS_MAPPINGS.update(TURBO_NODES)
NODE_DISPLAY_NAME_MAPPINGS.update(TURBO_NAMES)
from .exact_segment import NODE_CLASS_MAPPINGS as EXACT_NODES, NODE_DISPLAY_NAME_MAPPINGS as EXACT_NAMES
NODE_CLASS_MAPPINGS.update(EXACT_NODES)
NODE_DISPLAY_NAME_MAPPINGS.update(EXACT_NAMES)

NODE_CLASS_MAPPINGS.update(REFERENCE_NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(REFERENCE_NODE_DISPLAY_NAME_MAPPINGS)
NODE_CLASS_MAPPINGS.update(AUX_DEVICE_NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(AUX_DEVICE_NODE_DISPLAY_NAME_MAPPINGS)
NODE_CLASS_MAPPINGS.update(NORMALIZED_SAVE_NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(NORMALIZED_SAVE_NODE_DISPLAY_NAME_MAPPINGS)
NODE_CLASS_MAPPINGS.update(KEYFRAME_NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(KEYFRAME_NODE_DISPLAY_NAME_MAPPINGS)
NODE_CLASS_MAPPINGS.update(POSTPROCESS_NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(POSTPROCESS_NODE_DISPLAY_NAME_MAPPINGS)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
